Repository slackapi/deno-slack-api, pull requests merged in 2024-08, with the labels that each got.

#109 feat: add `event_timestamp` to all trigger event data objects
  src/typed-method-types/workflows/triggers/event-data/app_mentioned.ts
  src/typed-method-types/workflows/triggers/event-data/channel_archived.ts
  src/typed-method-types/workflows/triggers/event-data/channel_created.ts
  src/typed-method-types/workflows/triggers/event-data/channel_deleted.ts
  src/typed-method-types/workflows/triggers/event-data/channel_renamed.ts
  src/typed-method-types/workflows/triggers/event-data/channel_shared.ts
  src/typed-method-types/workflows/triggers/event-data/channel_unarchived.ts
  src/typed-method-types/workflows/triggers/event-data/channel_unshared.ts
  src/typed-method-types/workflows/triggers/event-data/common-objects/all_triggers.ts
  src/typed-method-types/workflows/triggers/event-data/dnd_updated.ts
  src/typed-method-types/workflows/triggers/event-data/emoji_changed.ts
  src/typed-method-types/workflows/triggers/event-data/message_metadata_posted.ts
  src/typed-method-types/workflows/triggers/event-data/message_posted.ts
  src/typed-method-types/workflows/triggers/event-data/pin_added.ts
  src/typed-method-types/workflows/triggers/event-data/pin_removed.ts
  src/typed-method-types/workflows/triggers/event-data/reaction_added.ts
  src/typed-method-types/workflows/triggers/event-data/reaction_removed.ts
  src/typed-method-types/workflows/triggers/event-data/shared_channel_invite_accepted.ts
  src/typed-method-types/workflows/triggers/event-data/shared_channel_invite_approved.ts
  src/typed-method-types/workflows/triggers/event-data/shared_channel_invite_declined.ts
  src/typed-method-types/workflows/triggers/event-data/shared_channel_invite_received.ts
  src/typed-method-types/workflows/triggers/event-data/user_joined_channel.ts
  src/typed-method-types/workflows/triggers/event-data/user_joined_team.ts
  src/typed-method-types/workflows/triggers/event-data/user_left_channel.ts
  src/typed-method-types/workflows/triggers/scheduled-data.ts
  src/typed-method-types/workflows/triggers/shortcut-data.ts
Labels: enhancement, semver:minor

#110 add JSR support
  .github/workflows/publish.yml
  .github/workflows/samples.yml
  deno.jsonc
  docs/client.md
  scripts/build_npm.ts
  scripts/import_map/update.ts
  scripts/import_map/update_test.ts
  scripts/src/generate.ts
  src/README.md
  src/api-proxy.ts
  src/api-proxy_test.ts
  src/api_test.ts
  src/base-client-helpers_test.ts
  src/base-client.ts
  src/deps.ts
  src/dev_deps.ts
  src/generated/method-types/api_method_types_test.ts
  src/generated/method-types/mod.ts
  src/mod.ts
  src/typed-method-types/apps.ts
  src/typed-method-types/chat.ts
  src/typed-method-types/functions.ts
  src/typed-method-types/mod.ts
  src/typed-method-types/typed-method-tests.ts
  src/typed-method-types/workflows/mod.ts
  src/typed-method-types/workflows/triggers/base_response.ts
  src/typed-method-types/workflows/triggers/event.ts
  src/typed-method-types/workflows/triggers/inputs.ts
  src/typed-method-types/workflows/triggers/mod.ts
  src/typed-method-types/workflows/triggers/scheduled.ts
  src/typed-method-types/workflows/triggers/shortcut.ts
  src/typed-method-types/workflows/triggers/tests/context_test.ts
  src/typed-method-types/workflows/triggers/tests/crud_test.ts
  src/typed-method-types/workflows/triggers/tests/event_test.ts
  src/typed-method-types/workflows/triggers/tests/scheduled_test.ts
  src/typed-method-types/workflows/triggers/tests/shortcut_test.ts
  src/typed-method-types/workflows/triggers/tests/trigger-filter_test.ts
  src/typed-method-types/workflows/triggers/tests/trigger-workflow_test.ts
  src/typed-method-types/workflows/triggers/tests/webhook_test.ts
  src/typed-method-types/workflows/triggers/webhook.ts
  src/types.ts
Labels: cla:signed

#79 Better dependency management, run tests against high and low version of deno
  .github/workflows/deno.yml
  .github/workflows/samples.yml
  scripts/src/import_map/update.ts
  scripts/src/import_map/update_test.ts
  src/typed-method-types/workflows/triggers/inputs.ts
  src/typed-method-types/workflows/triggers/tests/webhook_test.ts
Labels: enhancement, semver:patch
